### ISSUE TITLE
Wrong registry number

### ISSUE THREAD

**Issue by jiricodes** [jiricodes/corewar#26]
How to deal with wrong registry call? e.g. r50 as argument. Ignore, skip, error?

**Comment by Artemso** [comment]
There are two errors that can occur with the arguments:

1) Incorrect argument (ex r50). OP will step over the operation and its arguments.

2) Argument types don't match with OP definition. OP will load argtypes from the code, will not execute the operation, and will calculate a step according to the provided argtype_code. (this behaviour is discussed in the cookbook, end of the VM section).
